spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/angela
#    username: root
#    password: Leesohyun0102$
#    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    url: jdbc:mysql://localhost:3306/study
    username: root
    password: Felix1924!
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000
  openai:
    model: gpt-3.5-turbo
    secret-key: ${OPENAI_KEY}