spring:
  datasource:
    url: ${AWS_DB_ADDRESS}
    username: root
    password: ${AWS_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

  mail:
    host: smtp.gmail.com
    port: 587
    username: miindstonee@gmail.com
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

  jwt:
    secret-key: ${JWT_SECRET_KEY}

openai:
  model: gpt-3.5-turbo
  secret-key: ${OPENAI_KEY}

cloud:
  aws:
    s3:
      bucket: mindstonebucket
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${AWS_S3_ACCESSKEY}
      secretKey: ${AWS_S3_SECRETKEY}